# Generated by Django 5.0.8 on 2024-08-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_brand_alter_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='medi/'),
        ),
    ]
